### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by Amin-Tgz** [lgsvl/PythonAPI#1]
In Windows OS using **signal.SIGALRM** cause error
[Why is signal.SIGALRM not working in Python on windows?](https://stackoverflow.com/questions/52779920/why-is-signal-sigalrm-not-working-in-python-on-windows)

**Comment by martins-mozeiko** [comment]
Sorry for late reply.
SIGALRM is used only for unit tests which we develop on Linux.
Public API does not use this feature. If you are using Python API, you can safely ignore it.

**Comment by Ma5onic** [comment]
Note to windows users on how to work around this without commenting out code:
https://github.com/jeffbass/imagenode/issues/7#issue-673578509
