### ISSUE TITLE
enable Apollo's perception module for EGO

### ISSUE THREAD

**Issue by hyunjaecho94** [lgsvl/PythonAPI#11]
When I spawn an NPC vehicle in front of EGO and spawn EGO with a velocity, EGO will crash with the NPC, even though I enable the sensors. However, if Apollo's perception is active, it would realize that there is an obstacle in front and avoid craching into NPC. How can I enable this feature?

**Comment by martins-mozeiko** [comment]
Which feature? If you enable perception in EGO vehicle, and it is controlled by Apollo, then Apollo controls whether it will crash somewhere or not. This is not simulator responsibility, it is Apollo responsibility.

If perception does not run and/or Apollo is not controlling vehicle, then there's nobody that will stop EGO vehicle. Simulator expects AD stack to control the EGO vehicle.

**Comment by hyunjaecho94** [comment]
I understand that it is Apollo's responsibility. I was asking if it is possible to enable Apollo's AD stack using the Python API (or other ways) so that EGO avoids crashing into NPCs?
