### ISSUE TITLE
NPC rotation

### ISSUE THREAD

**Issue by hyunjaecho94** [lgsvl/PythonAPI#12]
Say I initialize a scene where an NPC is spawned 30 meters ahead of the EGO, and is given a set of waypoints to crash against the EGO (imagine the reverse of 13-npc-follow-waypoints.py, which spawns the NPC behind the EGO and the waypoints make the NPC pass through the EGO). When I do this, in order to make the NPC face the EGO, I give it a y-rotation of 180 degrees.
```
state = lgsvl.AgentState()
state.transform = spawns[0]
...
state.transform.rotation.y = 180.0
npc = sim.add_agent("Sedan", lgsvl.AgentType.NPC, state)
```
The NPC is spawned facing the EGO, which is what I want. However, it rotates after the scene is loaded, and drives in reverse when following its waypoints. I've tried several angles in DriveWaypoint(), but that does not seem to work, or my angles were incorrect. Could you please help me spot the problem? Thank you.

**Comment by martins-mozeiko** [comment]
The DriveWaypoint coordinates you are pass to `follow` call are in absolute world coordinates. You need to prepare these to have correct values regardless of angle you are passing to state.

Easiest way to do this is to launch simulator inside Unity Editor and while map is loaded, pause simulation and place object exactly where you want it to be, and then copy position & rotation values from Inspector window.

**Comment by hyunjaecho94** [comment]
I am unable to figure out the cause of NPC's rotation. I follow how 10-npc-follow-the-lane.py spawns the school bus facing to the right, (`state.transform.rotation.y=180.0` in my case) which spawns the NPC in the right direction.

In the video below, the NPC follows a set of waypoints, but in reverse mode. It is spawned facing the right direction, but as it starts to follow its waypoints, it turns to its right (between 8-12 seconds) and drives in reverse direction (12- seconds). If `npc.follow(waypoints)` is not called, the NPC does not rotate.

[npc_rotate.mkv.tar.gz](https://github.com/lgsvl/PythonAPI/files/3800905/npc_rotate.mkv.tar.gz)

Below is how I set NPC's waypoints, which is a close copy of how 13-npc-follow-waypoints.py sets its waypoints.

![npc-waypoint](https://user-images.githubusercontent.com/10676339/68076547-4ec08780-fd8c-11e9-84cc-33e51f1b7889.png)

**Comment by martins-mozeiko** [comment]
If we are talking about BorregaAve map, then in this map world X axis points towards left, and Z axis backwards. Basically X points towards east, Z towards north. You currently are creating points starting with (sx, sy, sz) position and next one located towards "backwards" direction. This is exactly what your video is showing.

Here's illustration on Google Maps:

![image](https://user-images.githubusercontent.com/39178216/68079742-cbaf2980-fdab-11e9-9ce9-05dfe3430715.png)

I strongly suggest you run Simulator inside Unity Editor to see how BorregaAve map looks like when it is loaded, so you understand where coordinates you are using are located. You can easily create new empty GameObject, position wherever you want and then write down its position.

Alternative would be to load HD map (Apollo, Autoware, Lanelet2 or OpenDrive format) and then get placement coordinates from lane positions inside map.

**Comment by hyunjaecho94** [comment]
I was able to obtain the positions I want NPC to follow but NPC still drives in reverse. When I change the direction from lgsvl.Vector(0, -1, 0) to lgsvl.Vector(0, 1, 0), I am unable to run the program due to `AttributeError: 'NoneType' object has no attribute 'point'` error.

Say I want my NPC to follow a set of waypoints. In the situation in the above video and the way I am setting those waypoints, how can I make NPC drive forward? Below is the code I've tried with sample waypoints (wpoints). 


```
waypoints = []
layer_mask = 0
layer_mask |= 1 << 0

wpoints = [lgsvl.Vector(13.8, -1.8, 0.52), lgsvl.Vector(13.8, -1.44, -35.86)]

for i in range(2):
  hit = sim.raycast(origin=wpoints[i],
  					direction=lgsvl.Vector(0, -1, 0),
  					layer_mask=layer_mask) 
  wp = lgsvl.DriveWaypoint(position=hit.point, speed=7)

  waypoints.append(wp)
```

**Comment by martins-mozeiko** [comment]
`lgsvl.Vector(0, -1, 0)` is direction of raycast. (0,-1,0) points downwards. You changed it to (0,1,0) - which means shoot ray up. It will hit nothing (only clouds), so it will return `None`.

If your positions are exactly where you want, you don't need to do the raycast functionality at all. You can directly pass these points to position argument.

Also when you were getting position of waypoints, you should get expected direction as Euler angles and put it to DriveWaypoint argument `angles`.

It should look like this:

    wpoints = [ \
        lgsvl.DriveWaypoint(position=lgsvl.Vector(p1x, p1y, p1z), angles=lgsvl.Vector(a1x, a1y, a1z), speed=s1),
        lgsvl.DriveWaypoint(position=lgsvl.Vector(p2x, p2y, p2z), angles=lgsvl.Vector(a2x, a2y, a2z), speed=s2),
        ... # repeat as needed
    ]

No raycast.

**Comment by hyunjaecho94** [comment]
Thank you. I was able to get it to work. However, I thought raycast was necessary because the ground is not flat, at least for Borregas Ave. How come do we not need to use raycast? As a result of this, the NPC floats when moving through certain parts of the map. Is there a way to make it stay on the ground?

**Comment by martins-mozeiko** [comment]
You need raycast if you are placing vehicles on unknown environment and know only approximate location where you want vehicle to be located. If you know exact 3d position where you want vehicle to be, you can specify directly in code without doing raycast.

And you can still do the raycast and specify the angle for DriveWaypoint constructor. Doing raycast does not prevent this.
