### ISSUE TITLE
How could I spawn pedestrians on the sidewalk?

### ISSUE THREAD

**Issue by orkop465** [lgsvl/PythonAPI#15]
Hello, I was wondering if there is any way to spawn pedestrians randomly on a sidewalk, instead of manually selecting coordinates, similar to sim.map_point_on_lane but for sidewalks. Thanks.

**Comment by martins-mozeiko** [comment]
Currently we do not have such functionality in Python API. You need to provide exact coordinates.

But it would be possible to add such function. Unity provides [NavMesh.SamplePosition](https://docs.unity3d.com/ScriptReference/AI.NavMesh.SamplePosition.html) function that could be used for this.
