### ISSUE TITLE
sim.get_spawn()  return none

### ISSUE THREAD

**Issue by david-gwa** [lgsvl/PythonAPI#2]
hey, lg guys,

thanks for this new version. I am interesting in the Python APIs as the previous version does.

 *  install lg-simulator 

 currently, I start the simulator.exe and click  `Use API to control simulation` 

![image](https://user-images.githubusercontent.com/52392538/64060325-8c265e80-cbfd-11e9-929b-aca59d7631a9.png)
     
*  download  [pythonAPI](https://github.com/lgsvl/PythonAPI) and  run  quickstart/04.py 

it reports error:

      Traceback (most recent call last):
    File "./quickstart/04-ego-drive-straight.py", line 20, in <module>
     state.transform = spawns[0]
      TypeError: 'NoneType' object is not subscriptable

I tried with different maps:  BorregasAve, SingleLand,  both give the same error.

**Comment by martins-mozeiko** [comment]
Can you please check the logfile of simulator when this exception happens? Log file location is here: https://www.lgsvlsimulator.com/docs/faq/#where-are-unity-log-files-located
It should have better information about the error.

**Comment by hyunjaecho94** [comment]
@martins-mozeiko I get a similar error when trying to run some of the quickstart scripts. For instance, 13-npc-follow-waypoints.py 

![13_error](https://user-images.githubusercontent.com/10676339/67239411-298f5900-f41d-11e9-8bfa-9ccf5c1194e0.png)

Which part of ~/.config/unity3d/Editor/Player.log should I be looking at?

**Comment by martins-mozeiko** [comment]
Can you please check what version of PythonAPI you are using? It must match Simulator version. For example, if you running simulator from 2019.09 version you cannot use PythonAPI from master. You need to take it also from 2019.09 tag. And vice versa.

**Comment by hyunjaecho94** [comment]
@martins-mozeiko 
After reading https://github.com/lgsvl/simulator/issues/422#issuecomment-539662872, I tried using both PythonAPI-2019.09 and PythonAPI-2019.07. However, this error is persistent in both versions. I am using the latest version of the simulator.

2019-09
![python09](https://user-images.githubusercontent.com/10676339/67248104-58172f00-f431-11e9-9baa-e74ffbadfef7.png)

2019.07
![python07](https://user-images.githubusercontent.com/10676339/67248105-59e0f280-f431-11e9-8186-48c8d55168da.png)

**Comment by martins-mozeiko** [comment]
PythonAPI does not have `if hit[0] is None` line in 216 of simulator.py from 2019.09 release. See here: https://github.com/lgsvl/PythonAPI/blob/2019.09/lgsvl/simulator.py#L196

You are most likely using Python API from master. Line 216 looks like that in master.
Try uninstalling PythonAPI package completely before installing older version. Then verify that simulator.py file does not have `if hit[0] is None` line inside.

**Comment by hyunjaecho94** [comment]
Thank you so much. It works now.
