### ISSUE TITLE
Send Frame to Python API

### ISSUE THREAD

**Issue by qsengshu** [lgsvl/PythonAPI#21]
Dear LGSVL,

Is it possible to send the main camera frame to the python api script?
Currently its only possible to use Sensor.save(). Which stores the Image but wont sent it through JSON. However, saving and reloading the camera image into python is a very slow operation.
 
Is there already a possibility here or do I have to extend the python api myself?

Best regards,
qsengshu

**Comment by rongguodong** [comment]
What do you mean by "send"? The camera sensor can already send the image over bridge. Is that what you want?

**Comment by qsengshu** [comment]
Yes. Couldnt find the command in the Python API. Do you have a link for me?

Best regards,
qsengshu

**Comment by rongguodong** [comment]
This is not done via Python command. You need to set the bridge in Vehicle setting page of WebUI, and set the topic name in JSON files. Please refer to this page for more details: https://www.lgsvlsimulator.com/docs/vehicles-tab/#bridge-types

**Comment by qsengshu** [comment]
Thanks for the link!

Best regards,
qsengshu
