### ISSUE TITLE
Problem adding random agents

### ISSUE THREAD

**Issue by andressa-suiti** [lgsvl/PythonAPI#22]
When I ran the example 29-add-random-agents, I received a message saying that the command "add_random_agents" (line 30) was unknown. It is executed normally until the data is sent with asyncio.run_coroutine_threadsafe (self.websocket.send (data), self.loop) in lgsvl / remote.py -> function "command". Then the output is {'error': "Ignoring unknown command 'simulator / add_random_agents'"}

**Comment by lemketron** [comment]
@andressa-suiti I have not seen or heard of this issue before. What version of the simulator are you using, and are you using the latest python-api? If this is still an issue you might want to try a fresh install of simulator and python api.
