### ISSUE TITLE
Branch Prefix : TypeError: descriptor '__subclasses__' of 'type' object needs an argument

### ISSUE THREAD

**Issue by SungYinYang** [lgsvl/PythonAPI#28]
Hi,

My computer is Ubuntu 16.04. GPU is RTX2080S.
I encounter the Type error problem when I tried to run the example in branch prefix.

`File "./quickstart/05-ego-drive-in-circle.py", line 8, in <module>
    from environs import Env
  File "/home/stevenubuntu/.local/lib/python3.5/site-packages/environs/__init__.py", line 32, in <module>
    Subcast = typing.Union[typing.Type, typing.Callable[..., _T]]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
`

![image](https://user-images.githubusercontent.com/54567577/99256316-2f3db500-2850-11eb-9dec-f9846fe54acd.png)

Any help or recommendation is appreciated!

My master branch is also not working at the same time.
I am able to execute the code, but the LGSVL simulator would show nothing.

**Comment by XuehuanYang** [comment]
Dear Yang,

I just tried the PythonAPI/quickstart/ from  https://github.com/lgsvl/PythonAPI/blob/master/quickstart/05-ego-drive-in-circle.py

$ python 05-ego-drive-in-circle.py

It **_successfully_** shows that he ego vehicle is driving in the circle today. 

**_Suggestions_**:  reinstall the PythonAPI source code and follow the **_README_** document

**Comment by SungYinYang** [comment]
@XuehuanYang 
I am trying on the branch preview.

Previously, my master branch works fine.
However, after I switch to the preview branch and then both master branch and preview branch does not work.

**Comment by SungYinYang** [comment]
Hi all, I think the problem is the python version.

My master branch work fine as I change it to python 3.5.2.

My prefix branch does not work in both python 3.8.6 and python 3.5.2
May I ask what version of branch are you working on?

**Comment by XuehuanYang** [comment]
Dear Yang, 

Current environment python version is 
**_Python 3.6.9 (default, Jul 17 2020)_**  **_[GCC 8.4.0] on linux_**
