### ISSUE TITLE
Can I run the simulator via PythonAPI headlessly?

### ISSUE THREAD

**Issue by cclinus** [lgsvl/PythonAPI#4]
Can I run the simulator via PythonAPI headlessly, without the graphic window showing every frame?

I'm automating some experiment using PythonAPI here and repeat the experiments, I don;t need look at GUI, every thing in the experiment is programmatically automated. So I am wondering if there are ways to run the simulation headlessly, and hence save some resources?

Thanks.

**Comment by zelenkovsky** [comment]
Yes, you can run simulation headlessly with API.

Place API Only & Headless Mode checkboxes when creating a new simulation according to documentation.

https://www.lgsvlsimulator.com/docs/simulations-tab/#how-to-addedit-a-simulation

Please let me know whether that answers your question.

**Comment by zelenkovsky** [comment]
BTW, you can run simulation faster then real-time as well, if needed: https://www.lgsvlsimulator.com/docs/python-api/#non-realtime-simulation

**Comment by cclinus** [comment]
Thanks @zelenkovsky .  That answers my question. 

Just to follow up, I am running apollo to drive ego car in lgsvl, and use lgsvl PythonApi to launch my experiments. Now with your answer, I can run lgsvl headlessly and programmatically, do you know how to run apollo headlessly using terminal as well, without using dreamviewer?

Thanks.

**Comment by cclinus** [comment]
Also can we do headless simulation in other versions of lgsvl? For example, in the version of 2019.05, which does not have a web gui interface.

**Comment by zelenkovsky** [comment]
No, only latest version supports faster then real-time and headless simulation.

Yes, we have code to control Apollo and run it without DreamView: enable modules one by one and set destination programmatically. I'll ask developers to share examples.

**Comment by cclinus** [comment]
@zelenkovsky Thanks! That would be super helpful if you can share the example code.

Btw, right now, I can launch headless mode of simulation via configuring from the web interface. In the future, if I want to run large-scale experiments on my GPU cluster using lgsvl, are there any ways I can do this via terminal, without using any GUI/web interface?

**Comment by lemketron** [comment]
@cclinus wrote:
> That would be super helpful if you can share the example code.

Update: We are working on integrating our DreamView control library into the python-api...

**Comment by GrayHHHH** [comment]
> @cclinus wrote:
> 
> > That would be super helpful if you can share the example code.
> 
> Update: We are working on integrating our DreamView control library into the python-api...

Thanks for updating the info. But I am not sure how to use for example set_destination() in dreamview module, could you please give some instructions?
