### ISSUE TITLE
Is there any way to use Python API in the Autoware.Ai-LGSVL simulator?

### ISSUE THREAD

**Issue by blacksheep0303** [lgsvl/PythonAPI#46]
I changed some codes of Autoware.Ai v1.14 and wanted to test them in the simulator.
So I need to build a suitable scene and customize pedestrians and vehicles.
Now I find that python-api only works when the simulator mode is API-ONLY.
So I want to ask how to use API with autoware connected.
Thanks!

**Comment by lemketron** [comment]
You can connect a sensor bridge using PythonAPI. There are several example scripts that demonstrate how to do this. 

You can find them in this search:
https://github.com/lgsvl/PythonAPI/search?q=bridge

**Comment by blacksheep0303** [comment]
@lemketron Thank you so much. I'll try it now.
