### ISSUE TITLE
How to record a simulation?

### ISSUE THREAD

**Issue by cclinus** [lgsvl/PythonAPI#5]
How to record a simulation, say as a video? Ideally, I want to record the simulation programmatically through API, is it possible?

Thanks.

**Comment by martins-mozeiko** [comment]
Easiest and most performant way would be to use [Geforce Experience](https://www.nvidia.com/en-us/geforce/geforce-experience/shadowplay/) video recording feature in Nvidia drivers. I don't think it has any API, but it can start/stop recording on keyboard shortcut. You could easily call [keybd_event](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-keybd_event) function to emulate pressing the necessary keys.

Alternative, for example on Linux, would be to call something like ffmpeg to record window from commandline: https://trac.ffmpeg.org/wiki/Capture/Desktop

**Comment by cclinus** [comment]
Thank you @martins-mozeiko
