### ISSUE TITLE
Save sensor data while executing Simulator.run()

### ISSUE THREAD

**Issue by zxrzju** [lgsvl/PythonAPI#53]
When executing `Simulator.run()`, the program is blocked.
 I tried to call `sensor.save()` in another thread, or used a python script to attach to the simulator and call `sensor.save()`. All the attempts didn't work. 
Can I save sensor data while executing `Simulator.run() `?

**Comment by lemketron** [comment]
Please note that sim.run() is a blocking call and does not return until a timeout or callback occurs, and you may not make other Python API calls into the Simulator from another thread. Between calls to sim.run() the simulator is not running.

Refer to https://github.com/lgsvl/simulator/issues/1674#issuecomment-894071118 for more details.

**Comment by zxrzju** [comment]
Thanks for your reply. I want to save compensated LiDAR point cloud. 
![image](https://user-images.githubusercontent.com/60004545/129849696-8f79c5b9-ec71-4653-8b04-aabdf38c902b.png)
But if I run a stepped simulation and call sensor.save(), it seems that the car is static even if the `compensated` property of LiDAR is `True`.  
![image](https://user-images.githubusercontent.com/60004545/129850389-b715874e-f854-4953-9037-e9e9d21df1db.png)
Can I get compensated LiDAR point cloud with Python API ?
