### ISSUE TITLE
How to manually control ego car?

### ISSUE THREAD

**Issue by cclinus** [lgsvl/PythonAPI#6]
How to manually control ego car? I saw in the documentation, it says user can manually control ego car, just like playing a video game where we can command the car using keyboard. Can anyone give me a line or two code example to do it? Thanks.

**Comment by zelenkovsky** [comment]
Hello, you can add Manual control sensor to the car:

https://www.lgsvlsimulator.com/docs/sensor-json-options/#manual-control

**Comment by cclinus** [comment]
@zelenkovsky Thanks, can we do that in previous versions of the simulator? I am using 2019.05 now, anyway to do it?

**Comment by martins-mozeiko** [comment]
In previous version of simulator car can be controlled by keyboard automatically if ROS is not sending any commands to vehicle. There is no code you need to write.

Note that we won't be supporting old version of simulator anymore. I suggest you upgrade to newest release.

**Comment by cclinus** [comment]
Thanks.
